version: "3.9"

services:
  meteostation:
    container_name: meteostation
    image: meteostation:latest
    hostname: meteostation
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - 5432:5432
      - 80:50000
    environment:
      POSTGRES_DB: meteostation
      POSTGRES_USER: meteostation
      POSTGRES_PASSWORD: meteostation
      PGDATA: /postgresql/data
    volumes:
      - ./data/postgres:/postgresql/data:rw
  redis:
    image: redis:alpine
    hostname: redis
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data:rw
    deploy:
#      replicas: 2
#      update_config:
#        parallelism: 2
#        delay: 10s
      restart_policy:
        condition: on-failure
    
networks:
  default:
    name: meteostation-net

volumes:
  pgdata:
#    driver: local
  rdata:
#    driver: local